name: Process new Documentation

on:
  repository_dispatch:
    types: [process_openapi]

jobs:
  process_openapi:
    runs-on: ubuntu-latest    
    steps:      
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.SPECS_REPO_PAT }}
      - name: Store new Documentation
        run: |
          export SPEC_PATH=specs/${{ github.event.client_payload.service }}/${{ github.event.client_payload.stage }}/${{ github.event.client_payload.version }}
          mkdir -p $SPEC_PATH
          echo "${{ github.event.client_payload.doc }}" | base64 -d > $SPEC_PATH/openapi.yml
      - name: Build Service Index
        uses: edgardleal/mustache-template-action@v1.0.0
        env:
          TITLE: ${{ github.event.client_payload.title }}
          STAGE: ${{ github.event.client_payload.stage }}
          VERSION: ${{ github.event.client_payload.version }}
        with:
          input: templates/service-index.tmpl
          output: specs/${{ github.event.client_payload.service }}/${{ github.event.client_payload.stage }}/${{ github.event.client_payload.version }}/index.html

      - name: Push Documentation
        run: |
          export SPEC_PATH=specs/${{ github.event.client_payload.service }}/${{ github.event.client_payload.stage }}/${{ github.event.client_payload.version }}
          git config --global user.email "redwolf@vizio.com"
          git config --global user.name "Redwolf CI"
          git add $SPEC_PATH/.
          git commit -am "Version ${{ github.event.client_payload.version }} of ${{ github.event.client_payload.service }} for ${{ github.event.client_payload.stage }} updated"
          git push origin main
