on:
  repository_dispatch:
    types: [process_openapi]

jobs:
  process_openapi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Store Spec
        run:
          - mkdir -p ${{ github.event.client_payload.service }}/${{ github.event.client_payload.version }}
          - echo "${{ github.event.client_payload.doc }}" | base64 -d > ${{ github.event.client_payload.service }}/${{ github.event.client_payload.version }}/openapi.yml
          - cp template.tmpl ${{ github.event.client_payload.service }}/${{ github.event.client_payload.version }}/index.html
      - name: Commit Spec
        run: |
          git add ${{ github.event.client_payload.service }}/${{ github.event.client_payload.version }}/.
          git commit -am "New version of ${{ github.event.client_payload.service }} documentation"
          git push
