on:
  repository_dispatch:
    types: [process_openapi]

jobs:
  process_openapi:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Store Spec
        run: |
          mkdir -p ${{ github.event.client_payload.service }}/${{ github.event.client_payload.version }}
          echo "${{ github.event.client_payload.doc }}" | base64 -d > ${{ github.event.client_payload.service }}/${{ github.event.client_payload.version }}/openapi.yml
          cp template.tmpl ${{ github.event.client_payload.service }}/${{ github.event.client_payload.version }}/index.html
      - name: Push Documentation 
        env:
          GITHUB_TOKEN: ${{ secrets.SPECS_REPO_PAT }}
          ISSUE_URL: ${{ github.event.issue.html_url }}

        run: |
          git config --global user.email "redwolf@vizio.com"
          git config --global user.name "Redwolf CI"
          git add ${{ github.event.client_payload.service }}/${{ github.event.client_payload.version }}/.
          git commit -am "New version of ${{ github.event.client_payload.service }} documentation"
          git push origin main
